<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Silk_Properties</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AngelCodeText\AngelCodeText.fsproj" />
      <ProjectReference Include="..\Asteroids\Asteroids.fsproj" />
      <ProjectReference Include="..\ConsoleLogger\ConsoleLogger.fsproj" />
      <ProjectReference Include="..\CSCoreAudio\CSCoreAudio.fsproj" />
      <ProjectReference Include="..\SilkGraphicsOGL\SilkGraphicsOGL.fsproj" />
      <ProjectReference Include="..\SilkInput\SilkInput.fsproj" />
      <ProjectReference Include="..\xUnitLogger\xUnitLogger.fsproj" />
    </ItemGroup>

</Project>
